platform :ios, "7.0"

target "CSNotificationViewDemo" do
  pod "CSNotificationView", :path => "../CSNotificationView.podspec"
end

target "CSNotificationViewTests" do
  pod "CSNotificationView", :path => "../CSNotificationView.podspec"
  pod "XCTAsyncTestCase", :git => "https://github.com/iheartradio/xctest-additions.git"
  pod "ReactiveCocoa", "~> 2.3.1"
end